name: Automate Unit Tests

on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install UV
              uses: astral-sh/setup-uv@v5
            - name: Install Dependencies
              run: uv sync
            - name: Run Unit Tests
              run: uv run pytest